/**
 * Lokarta: Come Into The Light - Game Worker
 * Authoritative Web Worker managing game state persistence, floor generation,
 * character progression, save slots, options, and settings storage.
 */

import {
  openStorage,
  read,
  put,
  getAll,
  deleteRecord,
  clearStore,
  readSlots,
  migrateLegacySave,
  migrateTowerSave,
  migratePartySave,
  now,
  STORES,
  MIGRATION_GUARD_KEY,
  TOWER_MIGRATION_GUARD_KEY,
  PARTY_MIGRATION_GUARD_KEY,
} from '../services/storage.js';
import {
  slotId,
  slotFloorKey,
  emptySlotRecord,
  deriveSlotMeta,
  snapshotFloorEntry,
  restoreFloorEntry,
  descendOnDeath,
  applyFullRestore,
  normalizeOptions,
  migratePlayerToTower,
  clampTowerFloor,
  SAVE_FORMAT_VERSION,
  OPTION_DEFAULTS,
  SAVE_SLOT_COUNT,
} from '../services/save-slots.js';
import { generateFloor, resolveArrivalCoords, FLOOR_TEMPLATE_VERSION, resolvePartySize } from '../services/floor-generator.js';
import {
  createPlayer,
  migratePlayerParty,
  captureActiveMember,
  normalizeTowerProgress,
  completePlayerTower,
  recruitMember,
  recruitableVocations,
  isTowerUnlocked,
  partySize as partySizeOf,
} from '../engine/index.js';
import { DEFAULT_TOWER_ID, getTowerDefinition } from '../data/index.js';

const OPTIONS_KEY = 'options';
const LAST_PLAYED_KEY = 'last_played_slot';

/**
 * True when the cached floor was generated by the current dungeon template;
 * false for floors baked by older templates (e.g. the legacy thick-walled
 * layout) that must be regenerated instead of replayed from IndexedDB.
 * @param {object|null} floor
 * @param {string|null} [towerId]
 * @param {number|null} [partySize] - live party size; when supplied, a floor
 *   scaled for a different size is stale (campaign.partyScale identity)
 * @returns {boolean}
 */
export function isStaleFloor(floor, towerId = null, partySize = null) {
  if (!floor) return true;
  if (floor.template_version !== FLOOR_TEMPLATE_VERSION) return true;
  // A cached floor belongs to exactly one tower: switching towers regenerates
  // and overwrites the slot's floor cache without an IndexedDB schema change.
  // A legacy record with no tower id is treated as the default tower.
  if (towerId && (floor.tower_id || DEFAULT_TOWER_ID) !== towerId) return true;
  // The campaign party curve is baked into each monster's hp/atk at generation
  // time, so the resolved party size is part of the floor's cache identity. A
  // missing `party_size` is a single-member floor; a freshly recruited member
  // (or a smaller party) must not replay a floor scaled for another size.
  if (partySize != null) {
    const cached = Math.floor(Number(floor.party_size)) || 1;
    if (cached !== Math.floor(Number(partySize))) return true;
  }
  return false;
}

/** Resolves a requested tower id to an authored tower id (falls back to default). */
function resolveTowerId(towerId) {
  const tower = getTowerDefinition(towerId);
  return tower ? tower.id : DEFAULT_TOWER_ID;
}

function clampFloor(value, towerId = DEFAULT_TOWER_ID) {
  return clampTowerFloor(value, towerId);
}

function clampSlotIndex(value) {
  const n = Math.floor(Number(value));
  if (!Number.isFinite(n) || n < 1 || n > SAVE_SLOT_COUNT) {
    throw new Error(`Invalid save slot index: ${value}`);
  }
  return n;
}

async function ensureProfile(soundEnabled = true) {
  let profile = await read(STORES.PROFILE, 'default_profile');
  if (!profile) {
    profile = {
      id: 'default_profile',
      soundEnabled,
      volume: 0.7,
      createdAt: now(),
      updatedAt: now(),
    };
    await put(STORES.PROFILE, profile);
  }
  return profile;
}

async function readOptionsRecord() {
  const record = await read(STORES.GAME_SETTINGS, OPTIONS_KEY);
  return normalizeOptions(record ? record.options : null);
}

async function persistOptions(options) {
  const profile = await ensureProfile(Boolean(options.soundEffects));
  profile.soundEnabled = Boolean(options.soundEffects);
  profile.updatedAt = now();
  await put(STORES.PROFILE, profile);
  await put(STORES.GAME_SETTINGS, {
    key: OPTIONS_KEY,
    version: 1,
    options,
    updatedAt: now(),
  });
  return options;
}

async function writeLastPlayed(slotIndex) {
  await put(STORES.GAME_SETTINGS, { key: LAST_PLAYED_KEY, slotIndex, updatedAt: now() });
}

async function readLastPlayed() {
  const record = await read(STORES.GAME_SETTINGS, LAST_PLAYED_KEY);
  return record ? record.slotIndex : null;
}

/**
 * Resolves a slot's live party size from its persisted character, clamped to
 * the authored campaign curve. Empty slots resolve to a single-member party.
 * @param {number} slotIndex
 * @returns {Promise<number>}
 */
async function readSlotPartySize(slotIndex) {
  const slot = await read(STORES.SAVE_SLOTS, slotId(slotIndex));
  if (!slot || !slot.characterId) return 1;
  const stored = await read(STORES.CHARACTERS, slot.characterId);
  return resolvePartySize(partySizeOf(stored));
}

/**
 * Loads a slot-scoped cached floor or generates and caches a fresh one.
 * The floor cache identity includes the resolved party size (via `party_size`
 * on the record), so recruiting never replays a pre-recruit floor.
 * @param {number} slotIndex
 * @param {number} floorNumber
 * @param {string} [towerId]
 * @param {boolean} [forceRegenerate=false]
 * @param {number|null} [partySize=null] - live party size; resolved from the
 *   slot's character when omitted
 * @returns {Promise<object>}
 */
async function loadOrGenerateSlotFloor(slotIndex, floorNumber, towerId = DEFAULT_TOWER_ID, forceRegenerate = false, partySize = null) {
  const resolvedTowerId = resolveTowerId(towerId);
  const fn = clampFloor(floorNumber, resolvedTowerId);
  const size = resolvePartySize(partySize == null ? await readSlotPartySize(slotIndex) : partySize);
  let floor = null;
  if (!forceRegenerate) {
    floor = await read(STORES.SLOT_FLOORS, slotFloorKey(slotIndex, fn));
    if (isStaleFloor(floor, resolvedTowerId, size)) floor = null;
  }
  if (!floor) {
    floor = generateFloor(fn, null, resolvedTowerId, size);
    floor.slotIndex = slotIndex;
    await put(STORES.SLOT_FLOORS, floor);
  }
  return floor;
}

function makeSlotPlayer(vocation, slotIndex) {
  const player = createPlayer(vocation, `char_slot_${slotIndex}`);
  const timestamp = now();
  player.slotId = slotId(slotIndex);
  player.slotIndex = slotIndex;
  player.saveVersion = SAVE_FORMAT_VERSION;
  player.playtimeMs = 0;
  player.createdAt = timestamp;
  player.updatedAt = timestamp;
  player.lastPlayedAt = timestamp;
  // Every save is a party save: one member at character creation, with only the
  // first tower unlocked. Capturing the active member keeps `party` in sync.
  return migratePlayerParty(player);
}

/**
 * Refreshes a slot's metadata from the current player state.
 * @returns {Promise<object|null>} updated slot record or null when unoccupied
 */
async function refreshSlot(slotIndex, player, biome, timestamp) {
  const existing = await read(STORES.SAVE_SLOTS, slotId(slotIndex));
  if (!existing || existing.status !== 'occupied') return null;
  const meta = deriveSlotMeta(player, slotIndex, biome || existing.biome);
  const updated = {
    ...existing,
    ...meta,
    createdAt: existing.createdAt || meta.createdAt || timestamp,
    lastPlayedAt: timestamp || meta.lastPlayedAt,
  };
  await put(STORES.SAVE_SLOTS, updated);
  return updated;
}

/**
 * Bootstraps game storage: profile, options, all save slots, and the last
 * played slot. Runs the v1 -> v2 migration once.
 * @returns {Promise<object>}
 */
async function handleBootstrap() {
  await openStorage();

  const profile = await ensureProfile();

  try {
    await migrateLegacySave();
  } catch (err) {
    console.warn('game-worker: legacy save migration failed; continuing with empty slots.', err);
  }

  // One-time 20 -> 5 tower migration: reset stale floor caches and clamp any
  // pre-tower character/slot onto the 5 levels. Runs after the slot migration
  // so a freshly migrated v1 save is also normalized.
  try {
    await migrateTowerSave();
  } catch (err) {
    console.warn('game-worker: tower save migration failed; saves will clamp on load.', err);
  }

  // One-time party migration (LIV-9): wrap legacy single-character saves into a
  // one-member party and initialize towerProgress. Runs after the tower
  // migration so a freshly normalized save is also party-migrated.
  try {
    await migratePartySave();
  } catch (err) {
    console.warn('game-worker: party save migration failed; saves will party-migrate on load.', err);
  }

  const options = await readOptionsRecord();
  const slots = await readSlots();
  const lastPlayedSlotIndex = await readLastPlayed();

  // Keep the profile's legacy sound flag in sync with the options model.
  if (profile.soundEnabled !== options.soundEffects) {
    profile.soundEnabled = options.soundEffects;
    profile.updatedAt = now();
    await put(STORES.PROFILE, profile);
  }

  return { profile, options, slots, lastPlayedSlotIndex };
}

/**
 * Returns the five save-slot metadata records.
 * @returns {Promise<{ slots: object[] }>}
 */
async function handleListSlots() {
  await openStorage();
  return { slots: await readSlots() };
}

/**
 * Creates a fresh character in the targeted slot.
 * @param {{ slotIndex: number, vocation?: string }} payload
 * @returns {Promise<{ player: object, floor: object, slot: object }>}
 */
async function handleCreateSlot(payload = {}) {
  const { vocation = 'magician' } = payload;
  const towerId = resolveTowerId(payload.towerId);
  const slotIndex = clampSlotIndex(payload.slotIndex);
  await openStorage();

  const player = makeSlotPlayer(vocation, slotIndex);
  player.towerId = towerId;
  const floor = generateFloor(1, null, towerId, partySizeOf(player));
  floor.slotIndex = slotIndex;
  if (floor.spawn_coords) {
    player.x = floor.spawn_coords.x;
    player.y = floor.spawn_coords.y;
  }
  player.current_floor = 1;
  player.floorEntry = snapshotFloorEntry(player);
  captureActiveMember(player);

  await put(STORES.CHARACTERS, player);
  await put(STORES.SLOT_FLOORS, floor);
  await put(STORES.DUNGEON_FLOORS, floor);

  const slot = deriveSlotMeta(player, slotIndex, floor.biome_name);
  await put(STORES.SAVE_SLOTS, slot);
  await writeLastPlayed(slotIndex);

  return { player, floor, slot };
}

/**
 * Selects a tower for an occupied slot: stamps the tower id, restarts the
 * character at that tower's level 1, regenerates its floor, and persists. Keys
 * and spring charges are per-run and reset so a fresh tower cannot inherit the
 * previous tower's progression.
 * @param {{ slotIndex: number, towerId: string }} payload
 * @returns {Promise<{ player: object, floor: object, slot: object }>}
 */
async function handleSelectTower(payload = {}) {
  const slotIndex = clampSlotIndex(payload.slotIndex);
  const towerId = resolveTowerId(payload.towerId);
  await openStorage();

  const slot = await read(STORES.SAVE_SLOTS, slotId(slotIndex));
  if (!slot || slot.status !== 'occupied' || !slot.characterId) {
    throw new Error(`Slot ${slotIndex} is empty.`);
  }
  const stored = await read(STORES.CHARACTERS, slot.characterId);
  if (!stored) {
    throw new Error(`Could not load Slot ${slotIndex}. Try again.`);
  }

  const player = migratePlayerParty({
    ...stored,
    towerId,
    current_floor: 1,
    levelKeys: {},
    springCharges: {},
    saveVersion: SAVE_FORMAT_VERSION,
  });
  // Campaign gate: a tower is only enterable once its prerequisites are
  // complete. Completed towers stay replayable; locked ones are rejected even
  // if a caller bypasses the picker.
  if (!isTowerUnlocked(player.towerProgress, towerId)) {
    throw new Error(`Tower '${towerId}' is locked — clear the previous tower first.`);
  }
  const floor = generateFloor(1, null, towerId, partySizeOf(player));
  floor.slotIndex = slotIndex;
  const start = floor.spawn_coords || floor.entrance;
  if (start) {
    player.x = start.x;
    player.y = start.y;
  }
  player.slotId = slotId(slotIndex);
  player.slotIndex = slotIndex;
  player.floorEntry = snapshotFloorEntry(player);
  const timestamp = now();
  player.updatedAt = timestamp;
  player.lastPlayedAt = timestamp;
  captureActiveMember(player);

  await put(STORES.CHARACTERS, player);
  await put(STORES.SLOT_FLOORS, floor);
  await put(STORES.DUNGEON_FLOORS, floor);
  const updatedSlot = await refreshSlot(slotIndex, player, floor.biome_name, timestamp);
  await writeLastPlayed(slotIndex);

  return { player, floor, slot: updatedSlot || slot };
}

/**
 * Records a tower completion for an occupied slot: marks the tower in
 * `towerProgress.completedTowerIds`, unlocks the next tower in campaign order,
 * and persists. Non-terminal: the caller decides whether this was the final
 * tower (allComplete) or should lead into the recruit flow.
 * @param {{ slotIndex: number, towerId?: string }} payload
 * @returns {Promise<{
 *   player: object, progress: object, completedTowerId: string|null,
 *   allComplete: boolean, nextTowerId: string|null, recruitableVocations: string[]
 * }>}
 */
async function handleCompleteTower(payload = {}) {
  const slotIndex = clampSlotIndex(payload.slotIndex);
  await openStorage();

  const slot = await read(STORES.SAVE_SLOTS, slotId(slotIndex));
  if (!slot || slot.status !== 'occupied' || !slot.characterId) {
    throw new Error(`Slot ${slotIndex} is empty.`);
  }
  let player = await read(STORES.CHARACTERS, slot.characterId);
  if (!player) {
    throw new Error(`Could not load Slot ${slotIndex}. Try again.`);
  }
  player = migratePlayerParty(player);

  const towerId = resolveTowerId(payload.towerId || player.towerId);
  const info = completePlayerTower(player, towerId);
  player.towerId = towerId;
  player.towerProgress = info.progress;
  player.slotId = slotId(slotIndex);
  player.slotIndex = slotIndex;
  player.saveVersion = SAVE_FORMAT_VERSION;
  const timestamp = now();
  player.updatedAt = timestamp;
  player.lastPlayedAt = timestamp;
  captureActiveMember(player);

  await put(STORES.CHARACTERS, player);
  await refreshSlot(slotIndex, player, null, timestamp);
  await writeLastPlayed(slotIndex);

  return {
    player,
    progress: player.towerProgress,
    completedTowerId: info.completedTowerId,
    allComplete: info.allComplete,
    nextTowerId: info.nextTowerId,
    recruitableVocations: recruitableVocations(player),
  };
}

/**
 * Recruits one vocation onto an occupied slot's party at level 1 (LIV-16),
 * appends it, makes it the active member, and persists. Starting at level 1
 * keeps the recruit eligible for the first Fate Grant, whose level-1 guarantee
 * offers a basic primary weapon.
 * @param {{ slotIndex: number, vocation: string }} payload
 * @returns {Promise<{ player: object, member: object, recruitableVocations: string[] }>}
 */
async function handleRecruitMember(payload = {}) {
  const slotIndex = clampSlotIndex(payload.slotIndex);
  await openStorage();

  const slot = await read(STORES.SAVE_SLOTS, slotId(slotIndex));
  if (!slot || slot.status !== 'occupied' || !slot.characterId) {
    throw new Error(`Slot ${slotIndex} is empty.`);
  }
  let player = await read(STORES.CHARACTERS, slot.characterId);
  if (!player) {
    throw new Error(`Could not load Slot ${slotIndex}. Try again.`);
  }
  player = migratePlayerParty(player);

  const member = recruitMember(player, payload.vocation);
  if (!member) {
    throw new Error(`Cannot recruit '${payload.vocation}' — unknown, already in the party, or the party is full.`);
  }

  player.slotId = slotId(slotIndex);
  player.slotIndex = slotIndex;
  player.saveVersion = SAVE_FORMAT_VERSION;
  const timestamp = now();
  player.updatedAt = timestamp;
  player.lastPlayedAt = timestamp;
  captureActiveMember(player);

  await put(STORES.CHARACTERS, player);
  await refreshSlot(slotIndex, player, null, timestamp);
  await writeLastPlayed(slotIndex);

  return { player, member, recruitableVocations: recruitableVocations(player) };
}

/**
 * Loads an occupied slot's character and current floor.
 * @param {{ slotIndex: number }} payload
 * @returns {Promise<{ player: object, floor: object, slot: object }>}
 */
async function handleLoadSlot(payload = {}) {
  const slotIndex = clampSlotIndex(payload.slotIndex);
  await openStorage();

  const slot = await read(STORES.SAVE_SLOTS, slotId(slotIndex));
  if (!slot || slot.status !== 'occupied') {
    throw new Error(`Slot ${slotIndex} is empty.`);
  }

  const stored = await read(STORES.CHARACTERS, slot.characterId);
  if (!stored) {
    throw new Error(`Could not load Slot ${slotIndex}. Try again.`);
  }
  // Clamp a pre-tower save (which may point past its tower's final level) onto
  // the selected tower and stamp the current save format before any floor is
  // generated or cached.
  const towerId = resolveTowerId(stored.towerId || slot.towerId);
  const player = migratePlayerParty({
    ...migratePlayerToTower(stored, towerId),
    towerId,
    saveVersion: SAVE_FORMAT_VERSION,
  });

  const floor = await loadOrGenerateSlotFloor(slotIndex, player.current_floor || 1, towerId, false, partySizeOf(player));
  // Continuing a save always starts at the level's start position,
  // regardless of where the player stood when last saved.
  const start = floor.spawn_coords || floor.entrance;
  if (start) {
    player.x = start.x;
    player.y = start.y;
  }
  player.floorEntry = snapshotFloorEntry(player);
  player.slotId = slotId(slotIndex);
  player.slotIndex = slotIndex;
  const timestamp = now();
  player.updatedAt = timestamp;
  player.lastPlayedAt = timestamp;
  captureActiveMember(player);

  await put(STORES.CHARACTERS, player);
  const updatedSlot = await refreshSlot(slotIndex, player, floor.biome_name, timestamp);
  await writeLastPlayed(slotIndex);

  return { player, floor, slot: updatedSlot || slot };
}

/**
 * Deletes a slot's character, metadata, and floor cache. Never touches the
 * legacy single-save stores.
 * @param {{ slotIndex: number }} payload
 * @returns {Promise<{ success: boolean }>}
 */
async function handleDeleteSlot(payload = {}) {
  const slotIndex = clampSlotIndex(payload.slotIndex);
  await openStorage();

  const slot = await read(STORES.SAVE_SLOTS, slotId(slotIndex));
  if (slot && slot.characterId) {
    await deleteRecord(STORES.CHARACTERS, slot.characterId);
  }
  await deleteRecord(STORES.SAVE_SLOTS, slotId(slotIndex));

  const floors = await getAll(STORES.SLOT_FLOORS);
  for (const floor of floors || []) {
    if (floor && floor.slotIndex === slotIndex) {
      await deleteRecord(STORES.SLOT_FLOORS, slotFloorKey(floor.slotIndex, floor.floor_number));
    }
  }

  if ((await readLastPlayed()) === slotIndex) {
    await deleteRecord(STORES.GAME_SETTINGS, LAST_PLAYED_KEY);
  }

  return { success: true };
}

/**
 * Restores a slot's floor-entry snapshot so the current floor restarts from
 * its arrival state.
 * @param {{ slotIndex: number }} payload
 * @returns {Promise<{ player: object, floor: object }>}
 */
async function handleRestartFloor(payload = {}) {
  const slotIndex = clampSlotIndex(payload.slotIndex);
  await openStorage();

  const slot = await read(STORES.SAVE_SLOTS, slotId(slotIndex));
  if (!slot || slot.status !== 'occupied' || !slot.characterId) {
    throw new Error(`Slot ${slotIndex} is empty.`);
  }
  let player = await read(STORES.CHARACTERS, slot.characterId);
  if (!player) {
    throw new Error(`Could not load Slot ${slotIndex}. Try again.`);
  }
  player = migratePlayerParty(player);

  const towerId = resolveTowerId(player.towerId || slot.towerId);
  player.towerId = towerId;
  // Clamp the pre-tower snapshot floor before restoring so a legacy floorEntry
  // can never put the player past the tower's final level.
  if (slot.floorEntry) {
    slot.floorEntry = { ...slot.floorEntry, current_floor: clampTowerFloor(slot.floorEntry.current_floor, towerId) };
  }
  restoreFloorEntry(player, slot.floorEntry);
  player.towerId = towerId;
  player.current_floor = clampTowerFloor(player.current_floor, towerId);
  player.slotId = slotId(slotIndex);
  player.slotIndex = slotIndex;
  player.saveVersion = SAVE_FORMAT_VERSION;
  const timestamp = now();
  player.updatedAt = timestamp;
  player.lastPlayedAt = timestamp;

  const floor = await loadOrGenerateSlotFloor(slotIndex, player.current_floor || 1, towerId, false, partySizeOf(player));
  if (floor.spawn_coords) {
    player.x = player.x ?? floor.spawn_coords.x;
    player.y = player.y ?? floor.spawn_coords.y;
  }
  player.floorEntry = snapshotFloorEntry(player);
  captureActiveMember(player);

  await put(STORES.CHARACTERS, player);
  await refreshSlot(slotIndex, player, floor.biome_name, timestamp);
  await writeLastPlayed(slotIndex);

  return { player, floor };
}

/**
 * Respawns a defeated player one level lower (never below level 1) with full
 * health and mana, landing at that level's start position.
 * @param {{ slotIndex: number }} payload
 * @returns {Promise<{ player: object, floor: object }>}
 */
async function handleRespawnAfterDeath(payload = {}) {
  const slotIndex = clampSlotIndex(payload.slotIndex);
  await openStorage();

  const slot = await read(STORES.SAVE_SLOTS, slotId(slotIndex));
  if (!slot || slot.status !== 'occupied' || !slot.characterId) {
    throw new Error(`Slot ${slotIndex} is empty.`);
  }
  let player = await read(STORES.CHARACTERS, slot.characterId);
  if (!player) {
    throw new Error(`Could not load Slot ${slotIndex}. Try again.`);
  }
  player = migratePlayerParty(player);

  player.towerId = resolveTowerId(player.towerId || slot.towerId);
  const respawnFloor = descendOnDeath(player);
  player.current_floor = respawnFloor;
  applyFullRestore(player);

  const floor = await loadOrGenerateSlotFloor(slotIndex, respawnFloor, player.towerId, false, partySizeOf(player));
  // Land at the level's start position (its entrance spawn / arrival from below).
  const start = resolveArrivalCoords(floor, respawnFloor - 1) || floor.spawn_coords || floor.entrance;
  if (start) {
    player.x = start.x;
    player.y = start.y;
  }

  player.slotId = slotId(slotIndex);
  player.slotIndex = slotIndex;
  player.saveVersion = SAVE_FORMAT_VERSION;
  player.floorEntry = snapshotFloorEntry(player);
  const timestamp = now();
  player.updatedAt = timestamp;
  player.lastPlayedAt = timestamp;
  captureActiveMember(player);

  await put(STORES.CHARACTERS, player);
  await refreshSlot(slotIndex, player, floor.biome_name, timestamp);
  await writeLastPlayed(slotIndex);

  return { player, floor };
}

/**
 * Legacy single-save new game (kept for backward compatibility).
 * @param {{ vocation?: string }} payload
 * @returns {Promise<{ player: object, floor: object }>}
 */
async function handleNewGame(payload = {}) {
  const { vocation = 'magician' } = payload;
  await openStorage();

  const towerId = resolveTowerId(payload.towerId);
  const player = migratePlayerParty(createPlayer(vocation));
  player.towerId = towerId;
  const currentTime = now();
  player.createdAt = currentTime;
  player.updatedAt = currentTime;
  player.playtimeMs = 0;

  const floor = generateFloor(1, null, towerId, partySizeOf(player));
  if (floor.spawn_coords) {
    player.x = floor.spawn_coords.x;
    player.y = floor.spawn_coords.y;
  }
  player.current_floor = 1;
  captureActiveMember(player);

  await put(STORES.CHARACTERS, player);
  await put(STORES.DUNGEON_FLOORS, floor);

  return { player, floor };
}

/**
 * Commits current player state, updating slot metadata when slot-scoped.
 * @param {{ player: object }} payload
 * @returns {Promise<{ success: boolean, savedAt: string }>}
 */
async function handleSaveCharacter(payload = {}) {
  const { player: incoming } = payload;
  if (!incoming) {
    throw new Error('Missing player object in saveCharacter payload.');
  }

  await openStorage();
  const savedAt = now();
  // Guarantee the party model exists even if the main thread sent a legacy
  // single-character object, then sync the live active state into `party`.
  const player = migratePlayerParty(incoming);
  player.updatedAt = savedAt;
  // Never persist a floor outside the player's tower, whatever the caller sent.
  player.current_floor = clampTowerFloor(player.current_floor, player.towerId);
  player.towerProgress = normalizeTowerProgress(player.towerProgress);
  player.saveVersion = SAVE_FORMAT_VERSION;
  captureActiveMember(player);

  await put(STORES.CHARACTERS, player);

  if (player.slotIndex) {
    await refreshSlot(player.slotIndex, player, null, player.lastPlayedAt || savedAt);
  }

  return { success: true, savedAt };
}

/**
 * Retrieves a cached floor (slot-scoped when slotIndex is provided) or
 * generates one with generateFloor.
 * @param {{ floorNumber?: number, slotIndex?: number, forceRegenerate?: boolean, partySize?: number }} payload
 * @returns {Promise<object>}
 */
async function handleGetFloor(payload = {}) {
  const { floorNumber = 1, slotIndex = null, forceRegenerate = false, partySize = null } = payload;
  const towerId = resolveTowerId(payload.towerId);
  await openStorage();

  if (slotIndex) {
    return loadOrGenerateSlotFloor(clampSlotIndex(slotIndex), floorNumber, towerId, forceRegenerate, partySize);
  }

  const fn = clampFloor(floorNumber, towerId);
  const size = resolvePartySize(partySize == null ? 1 : partySize);
  let floor = null;
  if (!forceRegenerate) {
    floor = await read(STORES.DUNGEON_FLOORS, fn);
    if (isStaleFloor(floor, towerId, size)) floor = null;
  }
  if (!floor) {
    floor = generateFloor(fn, null, towerId, size);
    await put(STORES.DUNGEON_FLOORS, floor);
  }
  return floor;
}

/**
 * Advances a player to the next floor, writing the arrival snapshot into
 * `floorEntry` and the slot metadata.
 * @param {{ player: object, nextFloorNumber?: number }} payload
 * @returns {Promise<{ player: object, floor: object }>}
 */
async function handleAdvanceFloor(payload = {}) {
  const { nextFloorNumber } = payload;
  let player = payload.player;
  if (!player) {
    throw new Error('Missing player object in advanceFloor payload.');
  }
  player = migratePlayerParty(player);

  await openStorage();

  const towerId = resolveTowerId(player.towerId);
  player.towerId = towerId;
  const currentFloor = Number(player.current_floor) || 1;
  const nextFloor = clampFloor(nextFloorNumber !== undefined ? nextFloorNumber : currentFloor + 1, towerId);
  const slotIndex = player.slotIndex || null;
  const livePartySize = resolvePartySize(partySizeOf(player));

  let floor;
  if (slotIndex) {
    floor = await loadOrGenerateSlotFloor(slotIndex, nextFloor, towerId, false, livePartySize);
  } else {
    floor = await read(STORES.DUNGEON_FLOORS, nextFloor);
    if (isStaleFloor(floor, towerId, livePartySize)) {
      floor = generateFloor(nextFloor, null, towerId, livePartySize);
      await put(STORES.DUNGEON_FLOORS, floor);
    }
  }

  player.current_floor = nextFloor;
  player.saveVersion = SAVE_FORMAT_VERSION;
  // Land on the target level's connecting stair (the "exit" seen from the level
  // left behind), not its entrance: from a lower level arrive at the up-stair,
  // from a higher level arrive at the down-stair (D2 §3).
  const arrival = resolveArrivalCoords(floor, currentFloor);
  if (arrival) {
    player.x = arrival.x;
    player.y = arrival.y;
  }
  player.floorEntry = snapshotFloorEntry(player);
  const timestamp = now();
  player.updatedAt = timestamp;
  player.lastPlayedAt = timestamp;
  captureActiveMember(player);

  await put(STORES.CHARACTERS, player);
  if (slotIndex) {
    await put(STORES.DUNGEON_FLOORS, floor);
    await refreshSlot(slotIndex, player, floor.biome_name, timestamp);
  }

  return { player, floor };
}

async function handleGetOptions() {
  await openStorage();
  return { options: await readOptionsRecord() };
}

/**
 * Merges an options patch over the persisted options, normalizes, and stores.
 * @param {{ patch?: object }} payload
 * @returns {Promise<{ options: object }>}
 */
async function handleSetOptions(payload = {}) {
  await openStorage();
  const base = await readOptionsRecord();
  const options = normalizeOptions({ ...base, ...(payload.patch || {}) });
  await persistOptions(options);
  return { options };
}

async function handleResetOptions() {
  await openStorage();
  const options = normalizeOptions(OPTION_DEFAULTS);
  await persistOptions(options);
  return { options };
}

/**
 * Legacy alias for `setOptions({ soundEffects })`.
 * @param {{ soundEnabled: boolean }} payload
 * @returns {Promise<{ options: object }>}
 */
async function handleSetSoundEnabled(payload = {}) {
  await openStorage();
  const base = await readOptionsRecord();
  const options = normalizeOptions({ ...base, soundEffects: Boolean(payload.soundEnabled) });
  await persistOptions(options);
  return { options };
}

/**
 * Clears characters and cached dungeon floors for a clean restart.
 * @returns {Promise<{ success: boolean }>}
 */
async function handleResetProgress() {
  await openStorage();

  await clearStore(STORES.CHARACTERS);
  await clearStore(STORES.DUNGEON_FLOORS);
  await clearStore(STORES.SAVE_SLOTS);
  await clearStore(STORES.SLOT_FLOORS);
  await deleteRecord(STORES.GAME_SETTINGS, MIGRATION_GUARD_KEY);
  await deleteRecord(STORES.GAME_SETTINGS, TOWER_MIGRATION_GUARD_KEY);
  await deleteRecord(STORES.GAME_SETTINGS, PARTY_MIGRATION_GUARD_KEY);
  await deleteRecord(STORES.GAME_SETTINGS, LAST_PLAYED_KEY);

  return { success: true };
}

/**
 * Persists chest opened-state for the player's current floor back into the
 * slot floor cache, so re-entering a level keeps opened chests empty. Accepts
 * the minimal chest-state records (see ChestSystem.serializeChestState) and
 * merges them onto the cached floor without touching tiles/entities.
 * @param {{ player?: object, chests?: object[] }} payload
 * @returns {Promise<{ success: boolean }>}
 */
async function handleSaveFloorState(payload = {}) {
  const { player, chests } = payload;
  if (!player) {
    throw new Error('Missing player object in saveFloorState payload.');
  }
  await openStorage();

  const floorNumber = clampFloor(player.current_floor || 1, player.towerId);
  const slotIndex = player.slotIndex || null;
  const floor = slotIndex
    ? await read(STORES.SLOT_FLOORS, slotFloorKey(slotIndex, floorNumber))
    : await read(STORES.DUNGEON_FLOORS, floorNumber);
  if (!floor) return { success: false };

  floor.chests = Array.isArray(chests) ? chests : floor.chests || [];
  await put(slotIndex ? STORES.SLOT_FLOORS : STORES.DUNGEON_FLOORS, floor);
  return { success: true };
}

// Exported for the native test runner (the worker-safe module still guards its
// `self.onmessage` hook below, so importing this in Node is inert).
export const COMMAND_HANDLERS = {
  bootstrap: handleBootstrap,
  listSlots: handleListSlots,
  createSlot: handleCreateSlot,
  loadSlot: handleLoadSlot,
  selectTower: handleSelectTower,
  completeTower: handleCompleteTower,
  recruitMember: handleRecruitMember,
  deleteSlot: handleDeleteSlot,
  restartFloor: handleRestartFloor,
  respawnAfterDeath: handleRespawnAfterDeath,
  newGame: handleNewGame,
  saveCharacter: handleSaveCharacter,
  getFloor: handleGetFloor,
  saveFloorState: handleSaveFloorState,
  advanceFloor: handleAdvanceFloor,
  getOptions: handleGetOptions,
  setOptions: handleSetOptions,
  resetOptions: handleResetOptions,
  setSoundEnabled: handleSetSoundEnabled,
  resetProgress: handleResetProgress,
};

/**
 * Worker message event listener.
 * Protocol:
 * Incoming: { id: string|number, command: string, payload: object }
 * Outgoing: { id: string|number, ok: boolean, data?: any, error?: string }
 */
if (typeof self !== 'undefined') {
  self.onmessage = async ({ data }) => {
    const { id, command, payload = {} } = data || {};

    if (id === undefined || id === null) {
      console.error('game-worker: received message without request ID:', data);
      return;
    }

    try {
      const handler = COMMAND_HANDLERS[command];
      if (!handler) {
        throw new Error(`Unknown worker command: '${command}'`);
      }

      const result = await handler(payload);
      self.postMessage({ id, ok: true, data: result });
    } catch (err) {
      self.postMessage({
        id,
        ok: false,
        error: err instanceof Error ? err.message : String(err),
      });
    }
  };
}
