/**
 * Lokarta: Come Into The Light - Chest Subsystem
 *
 * Chests are world entities generated by the floor generator per D2 §7:
 * exactly one per room, tiered copper/silver/gold, each carrying a loot roll
 * from `html/data/chests.json`. This module owns the pure open interaction and
 * the save/load-compatible state helpers. It performs no DOM, worker, or
 * storage I/O so it can be exercised from the native Node test runner.
 */

import { rollChestLoot, createPRNG } from '../services/floor-generator.js';

/** Default opener used when a chest is opened without an explicit vocation. */
const FALLBACK_VOCATION = 'neutral';

/**
 * Finds the chest occupying a grid tile, if any.
 * @param {object[]} chests
 * @param {number} x
 * @param {number} y
 * @returns {object|null}
 */
export function findChestAt(chests, x, y) {
  if (!Array.isArray(chests)) return null;
  for (const chest of chests) {
    if (chest && chest.x === x && chest.y === y) return chest;
  }
  return null;
}

/**
 * True when a chest can still be opened (present and not yet opened).
 * @param {object|null} chest
 * @returns {boolean}
 */
export function isChestOpenable(chest) {
  return Boolean(chest) && chest.opened !== true;
}

/**
 * Opens a chest: rolls its tiered loot for the opener's vocation, flips the
 * `opened` flag, and returns the loot. Opening an already-opened chest is a
 * no-op (`success: false`) so interaction is idempotent across re-entry.
 *
 * @param {object} chest - generated chest entity
 * @param {object} [opts]
 * @param {string} [opts.vocation] - opener vocation for smart loot
 * @param {Function} [opts.rng] - deterministic PRNG (createPRNG-compatible)
 * @returns {{ success: boolean, loot: object[], message: string }}
 */
export function openChest(chest, opts = {}) {
  if (!chest) {
    return { success: false, loot: [], message: 'There is no chest here.' };
  }
  if (chest.opened === true) {
    return { success: false, loot: [], message: 'This chest is already empty.' };
  }

  const loot = rollChestLoot(chest.tier, {
    vocation: opts.vocation || FALLBACK_VOCATION,
    // Distinct chests roll distinct, reproducible contents. Callers may inject
    // an explicit rng for cross-session determinism.
    rng: opts.rng || createPRNG(`chest:${chest.id || `${chest.x},${chest.y}`}:${chest.tier}`),
  });
  chest.opened = true;

  const label = loot.length === 1 ? 'item' : 'items';
  return {
    success: true,
    loot,
    message: `Opened the ${chest.tier} chest — found ${loot.length} ${label}.`,
  };
}

/**
 * Restores opened-state flags from a persisted floor snapshot onto freshly
 * generated chests. Matches by chest id first (stable within a level), then by
 * room, so a save survives a template that re-shuffles tile coordinates.
 * Mutates and returns `chests`.
 *
 * @param {object[]} chests - freshly generated chests
 * @param {object[]} persisted - chest records loaded from storage
 * @returns {object[]}
 */
export function applyOpenedState(chests, persisted) {
  if (!Array.isArray(chests)) return [];
  if (!Array.isArray(persisted) || persisted.length === 0) return chests;

  const byId = new Map();
  const byRoomTier = new Map();
  for (const record of persisted) {
    if (!record) continue;
    if (record.id) byId.set(record.id, record);
    if (record.room !== undefined && record.tier) {
      byRoomTier.set(`${record.room}:${record.tier}`, record);
    }
  }

  for (const chest of chests) {
    const match =
      byId.get(chest.id) || byRoomTier.get(`${chest.room}:${chest.tier}`);
    if (match && match.opened === true) chest.opened = true;
  }
  return chests;
}

/**
 * Serializes only the durable chest state (id/room/tier/opened) so a floor
 * cache stays small and forward-compatible.
 * @param {object[]} chests
 * @returns {object[]}
 */
export function serializeChestState(chests) {
  if (!Array.isArray(chests)) return [];
  return chests.map(chest => ({
    id: chest.id,
    room: chest.room,
    tier: chest.tier,
    opened: chest.opened === true,
  }));
}

export class ChestSystem {
  static findChestAt = findChestAt;
  static isChestOpenable = isChestOpenable;
  static openChest = openChest;
  static applyOpenedState = applyOpenedState;
  static serializeChestState = serializeChestState;
}
